language: node_js
node_js:
  - "node"
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - "lts/carbon"
  - "lts/dubnium"
  - "lts/erbium"
os:
  - linux
  - osx
script: npm test
cache: npm
matrix:
  fast_finish: true
